#!/bin/csh -x

set MAYAPLUGINS = /usr/autodesk/maya2014-x64/devkit/plug-ins/
set MAYAINCLUDE = /usr/autodesk/maya2014-x64/include
set MAYALIBS = /usr/autodesk/maya2014-x64/lib
set EMBREEROOT = /nfs/pdx/home/cwcongdo/Programming/dcc_render-embree
set RENDERROOT = /nfs/pdx/home/cwcongdo/Programming/dcc_render-dcc_render-ccongdon-embree-renderer
set INTELCOMPOSERXEROOT = /opt/intel/composer_xe_2015.0.090
# set INTELCOMPOSERXEROOT = /opt/intel/composer_xe_2013_sp1.3.174
set INTELCOMPILERLIBS = $INTELCOMPOSERXEROOT/compiler/lib/intel64

echo ""
echo ""

#cc -c -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-dcc_render-ccongdon-embree-renderer -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-dcc_render-ccongdon-embree-renderer/common -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-embree -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-dcc_render-ccongdon-embree-renderer/devices -I../EmbreeViewportRenderer -I/usr/autodesk/maya2014-x64/include -I/usr/X11R6/include  -DBits64_ -m64 -DUNIX -D_BOOL -DLINUX -DFUNCPROTO -D_GNU_SOURCE -DLINUX_64 -fPIC -fno-strict-aliasing -DREQUIRE_IOSTREAM -O3 -Wall -Wno-multichar -Wno-comment -Wno-sign-compare -funsigned-char -pthread -g  ../EmbreeViewportRenderer/EmbreeViewportRenderer.cpp -o ../build/EmbreeViewportRenderer.o
cc -c -I$RENDERROOT -I$RENDERROOT/common -I$EMBREEROOT -I$RENDERROOT/devices -I../EmbreeViewportRenderer -I$MAYAINCLUDE -I/usr/X11R6/include  -DBits64_ -m64 -DUNIX -D_BOOL -DLINUX -DFUNCPROTO -D_GNU_SOURCE -DLINUX_64 -fPIC -fno-strict-aliasing -DREQUIRE_IOSTREAM -O3 -Wall -Wno-multichar -Wno-comment -Wno-sign-compare -funsigned-char -pthread -g  ../EmbreeViewportRenderer/EmbreeViewportRenderer.cpp -o ../build/EmbreeViewportRenderer.o

echo ""
echo "Build the single-ray viewport renderer for Intel(r) Xeon(r) plugin"
echo ""

#cc -c -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-dcc_render-ccongdon-embree-renderer -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-dcc_render-ccongdon-embree-renderer/common -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-embree -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-dcc_render-ccongdon-embree-renderer/devices -I../EmbreeViewportRenderer -I/usr/autodesk/maya2014-x64/include -I/usr/X11R6/include  -DBits64_ -m64 -DUNIX -D_BOOL -DLINUX -DFUNCPROTO -D_GNU_SOURCE -DLINUX_64 -fPIC -fno-strict-aliasing -DREQUIRE_IOSTREAM -O3 -Wall -Wno-multichar -Wno-comment -Wno-sign-compare -funsigned-char -pthread -g  -DSINGLEXEON ../EmbreeViewportRenderer/EmbreeViewportRendererPlugin.cpp -o ../build/EmbreeViewportRendererPluginSX.o
cc -c -I$RENDERROOT -I$RENDERROOT/common -I$EMBREEROOT -I$RENDERROOT/devices -I../EmbreeViewportRenderer -I$MAYAINCLUDE -I/usr/X11R6/include  -DBits64_ -m64 -DUNIX -D_BOOL -DLINUX -DFUNCPROTO -D_GNU_SOURCE -DLINUX_64 -fPIC -fno-strict-aliasing -DREQUIRE_IOSTREAM -O3 -Wall -Wno-multichar -Wno-comment -Wno-sign-compare -funsigned-char -pthread -g  -DSINGLEXEON ../EmbreeViewportRenderer/EmbreeViewportRendererPlugin.cpp -o ../build/EmbreeViewportRendererPluginSX.o

rm -f ../build/EmbreeViewportRendererSX.so

#cc  -o ../build/EmbreeViewportRendererSX.so -DBits64_ -m64 -DUNIX -D_BOOL -DLINUX -DFUNCPROTO -D_GNU_SOURCE -DLINUX_64 -fPIC -fno-strict-aliasing -DREQUIRE_IOSTREAM -O3 -Wall -Wno-multichar -Wno-comment -Wno-sign-compare -funsigned-char -pthread -g   -Wno-deprecated -Wno-reorder -ftemplate-depth-25 -fno-gnu-keywords -Wl,-Bsymbolic -shared -Wl,--version-script=../EmbreeViewportRenderer/linux_plugin.map -L../build -L/usr/autodesk/maya2014-x64/lib   ../build/EmbreeViewportRenderer.o ../build/EmbreeViewportRendererPluginSX.o -L/usr/autodesk/maya2014-x64/lib   -lOpenMayaRender -lOpenMaya -lOpenMayaUI -lFoundation ../build/libsys.a ../build/liblexers.a ../build/libloaders.a ../build/libimage.a ../build/libdevice.a ../build/liblexers.a ../build/libsys.a -lpthread -ldl   /opt/intel/composer_xe_2015.0.090/compiler/lib/intel64/libimf.a /opt/intel/composer_xe_2015.0.090/compiler/lib/intel64/libirc.a
cc  -o ../build/EmbreeViewportRendererSX.so -DBits64_ -m64 -DUNIX -D_BOOL -DLINUX -DFUNCPROTO -D_GNU_SOURCE -DLINUX_64 -fPIC -fno-strict-aliasing -DREQUIRE_IOSTREAM -O3 -Wall -Wno-multichar -Wno-comment -Wno-sign-compare -funsigned-char -pthread -g   -Wno-deprecated -Wno-reorder -ftemplate-depth-25 -fno-gnu-keywords -Wl,-Bsymbolic -shared -Wl,--version-script=$MAYAPLUGINS/linux_plugin.map -L../build -L$MAYALIBS   ../build/EmbreeViewportRenderer.o ../build/EmbreeViewportRendererPluginSX.o -L$MAYALIBS   -lOpenMayaRender -lOpenMaya -lOpenMayaUI -lFoundation ../build/libsys.a ../build/liblexers.a ../build/libloaders.a ../build/libimage.a ../build/libdevice.a ../build/liblexers.a ../build/libsys.a -lpthread -ldl   $INTELCOMPILERLIBS/libimf.a $INTELCOMPILERLIBS/libirc.a

echo ""
echo "Build the ISPC viewport renderer for Intel(r) Xeon(r) plugin"
echo ""

#cc -c -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-dcc_render-ccongdon-embree-renderer -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-dcc_render-ccongdon-embree-renderer/common -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-embree -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-dcc_render-ccongdon-embree-renderer/devices -I../EmbreeViewportRenderer -I/usr/autodesk/maya2014-x64/include -I/usr/X11R6/include  -DBits64_ -m64 -DUNIX -D_BOOL -DLINUX -DFUNCPROTO -D_GNU_SOURCE -DLINUX_64 -fPIC -fno-strict-aliasing -DREQUIRE_IOSTREAM -O3 -Wall -Wno-multichar -Wno-comment -Wno-sign-compare -funsigned-char -pthread -g  -DISPCXEON ../EmbreeViewportRenderer/EmbreeViewportRendererPlugin.cpp -o ../build/EmbreeViewportRendererPluginIX.o
cc -c -I$RENDERROOT -I$RENDERROOT/common -I$EMBREEROOT -I$RENDERROOT/devices -I../EmbreeViewportRenderer -I$MAYAINCLUDE -I/usr/X11R6/include  -DBits64_ -m64 -DUNIX -D_BOOL -DLINUX -DFUNCPROTO -D_GNU_SOURCE -DLINUX_64 -fPIC -fno-strict-aliasing -DREQUIRE_IOSTREAM -O3 -Wall -Wno-multichar -Wno-comment -Wno-sign-compare -funsigned-char -pthread -g  -DISPCXEON ../EmbreeViewportRenderer/EmbreeViewportRendererPlugin.cpp -o ../build/EmbreeViewportRendererPluginIX.o

rm -f ../build/EmbreeViewportRendererIX.so

#cc  -o ../build/EmbreeViewportRendererIX.so -DBits64_ -m64 -DUNIX -D_BOOL -DLINUX -DFUNCPROTO -D_GNU_SOURCE -DLINUX_64 -fPIC -fno-strict-aliasing -DREQUIRE_IOSTREAM -O3 -Wall -Wno-multichar -Wno-comment -Wno-sign-compare -funsigned-char -pthread -g   -Wno-deprecated -Wno-reorder -ftemplate-depth-25 -fno-gnu-keywords -Wl,-Bsymbolic -shared -Wl,--version-script=../EmbreeViewportRenderer/linux_plugin.map -L../build -L/usr/autodesk/maya2014-x64/lib   ../build/EmbreeViewportRenderer.o ../build/EmbreeViewportRendererPluginIX.o -L/usr/autodesk/maya2014-x64/lib   -lOpenMayaRender -lOpenMaya -lOpenMayaUI -lFoundation ../build/libsys.a ../build/liblexers.a ../build/libloaders.a ../build/libimage.a ../build/libdevice.a ../build/liblexers.a ../build/libsys.a -lpthread -ldl   /opt/intel/composer_xe_2015.0.090/compiler/lib/intel64/libimf.a /opt/intel/composer_xe_2015.0.090/compiler/lib/intel64/libirc.a
cc  -o ../build/EmbreeViewportRendererIX.so -DBits64_ -m64 -DUNIX -D_BOOL -DLINUX -DFUNCPROTO -D_GNU_SOURCE -DLINUX_64 -fPIC -fno-strict-aliasing -DREQUIRE_IOSTREAM -O3 -Wall -Wno-multichar -Wno-comment -Wno-sign-compare -funsigned-char -pthread -g   -Wno-deprecated -Wno-reorder -ftemplate-depth-25 -fno-gnu-keywords -Wl,-Bsymbolic -shared -Wl,--version-script=$MAYAPLUGINS/linux_plugin.map -L../build -L$MAYALIBS   ../build/EmbreeViewportRenderer.o ../build/EmbreeViewportRendererPluginIX.o -L$MAYALIBS   -lOpenMayaRender -lOpenMaya -lOpenMayaUI -lFoundation ../build/libsys.a ../build/liblexers.a ../build/libloaders.a ../build/libimage.a ../build/libdevice.a ../build/liblexers.a ../build/libsys.a -lpthread -ldl  $INTELCOMPILERLIBS/libimf.a $INTELCOMPILERLIBS/libirc.a

echo ""
echo "Build the single-ray viewport renderer for Intel(r) Xeon Phi(tm) plugin"
echo ""

#cc -c -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-dcc_render-ccongdon-embree-renderer -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-dcc_render-ccongdon-embree-renderer/common -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-embree -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-dcc_render-ccongdon-embree-renderer/devices -I../EmbreeViewportRenderer -I/usr/autodesk/maya2014-x64/include -I/usr/X11R6/include  -DBits64_ -m64 -DUNIX -D_BOOL -DLINUX -DFUNCPROTO -D_GNU_SOURCE -DLINUX_64 -fPIC -fno-strict-aliasing -DREQUIRE_IOSTREAM -O3 -Wall -Wno-multichar -Wno-comment -Wno-sign-compare -funsigned-char -pthread -g  -DSINGLEXEONPHI ../EmbreeViewportRenderer/EmbreeViewportRendererPlugin.cpp -o ../build/EmbreeViewportRendererPluginSXP.o
cc -c -I$RENDERROOT -I$RENDERROOT/common -I$EMBREEROOT -I$RENDERROOT/devices -I../EmbreeViewportRenderer -I$MAYAINCLUDE -I/usr/X11R6/include  -DBits64_ -m64 -DUNIX -D_BOOL -DLINUX -DFUNCPROTO -D_GNU_SOURCE -DLINUX_64 -fPIC -fno-strict-aliasing -DREQUIRE_IOSTREAM -O3 -Wall -Wno-multichar -Wno-comment -Wno-sign-compare -funsigned-char -pthread -g  -DSINGLEXEONPHI ../EmbreeViewportRenderer/EmbreeViewportRendererPlugin.cpp -o ../build/EmbreeViewportRendererPluginSXP.o

rm -f ../build/EmbreeViewportRendererSXP.so

#cc  -o ../build/EmbreeViewportRendererSXP.so -DBits64_ -m64 -DUNIX -D_BOOL -DLINUX -DFUNCPROTO -D_GNU_SOURCE -DLINUX_64 -fPIC -fno-strict-aliasing -DREQUIRE_IOSTREAM -O3 -Wall -Wno-multichar -Wno-comment -Wno-sign-compare -funsigned-char -pthread -g   -Wno-deprecated -Wno-reorder -ftemplate-depth-25 -fno-gnu-keywords -Wl,-Bsymbolic -shared -Wl,--version-script=../EmbreeViewportRenderer/linux_plugin.map -L../build -L/usr/autodesk/maya2014-x64/lib   ../build/EmbreeViewportRenderer.o ../build/EmbreeViewportRendererPluginSXP.o -L/usr/autodesk/maya2014-x64/lib   -lOpenMayaRender -lOpenMaya -lOpenMayaUI -lFoundation ../build/libsys.a ../build/liblexers.a ../build/libloaders.a ../build/libimage.a ../build/libdevice.a ../build/liblexers.a ../build/libsys.a -lpthread -ldl   /opt/intel/composer_xe_2015.0.090/compiler/lib/intel64/libimf.a /opt/intel/composer_xe_2015.0.090/compiler/lib/intel64/libirc.a
cc  -o ../build/EmbreeViewportRendererSXP.so -DBits64_ -m64 -DUNIX -D_BOOL -DLINUX -DFUNCPROTO -D_GNU_SOURCE -DLINUX_64 -fPIC -fno-strict-aliasing -DREQUIRE_IOSTREAM -O3 -Wall -Wno-multichar -Wno-comment -Wno-sign-compare -funsigned-char -pthread -g   -Wno-deprecated -Wno-reorder -ftemplate-depth-25 -fno-gnu-keywords -Wl,-Bsymbolic -shared -Wl,--version-script=$MAYAPLUGINS/linux_plugin.map -L../build -L$MAYALIBS   ../build/EmbreeViewportRenderer.o ../build/EmbreeViewportRendererPluginSXP.o -L$MAYALIBS   -lOpenMayaRender -lOpenMaya -lOpenMayaUI -lFoundation ../build/libsys.a ../build/liblexers.a ../build/libloaders.a ../build/libimage.a ../build/libdevice.a ../build/liblexers.a ../build/libsys.a -lpthread -ldl  $INTELCOMPILERLIBS/libimf.a $INTELCOMPILERLIBS/libirc.a 

echo ""
echo "Build the ISPC viewport renderer for Intel(r) Xeon Phi(tm) plugin"
echo ""

#cc -c -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-dcc_render-ccongdon-embree-renderer -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-dcc_render-ccongdon-embree-renderer/common -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-embree -I/nfs/pdx/home/cwcongdo/Programming/dcc_render-dcc_render-ccongdon-embree-renderer/devices -I../EmbreeViewportRenderer -I/usr/autodesk/maya2014-x64/include -I/usr/X11R6/include  -DBits64_ -m64 -DUNIX -D_BOOL -DLINUX -DFUNCPROTO -D_GNU_SOURCE -DLINUX_64 -fPIC -fno-strict-aliasing -DREQUIRE_IOSTREAM -O3 -Wall -Wno-multichar -Wno-comment -Wno-sign-compare -funsigned-char -pthread -g  -DISPCXEONPHI ../EmbreeViewportRenderer/EmbreeViewportRendererPlugin.cpp -o ../build/EmbreeViewportRendererPluginIXP.o
cc -c -I$RENDERROOT -I$RENDERROOT/common -I$EMBREEROOT -I$RENDERROOT/devices -I../EmbreeViewportRenderer -I$MAYAINCLUDE -I/usr/X11R6/include  -DBits64_ -m64 -DUNIX -D_BOOL -DLINUX -DFUNCPROTO -D_GNU_SOURCE -DLINUX_64 -fPIC -fno-strict-aliasing -DREQUIRE_IOSTREAM -O3 -Wall -Wno-multichar -Wno-comment -Wno-sign-compare -funsigned-char -pthread -g  -DISPCXEONPHI ../EmbreeViewportRenderer/EmbreeViewportRendererPlugin.cpp -o ../build/EmbreeViewportRendererPluginIXP.o

rm -f ../build/EmbreeViewportRendererIXP.so

#cc  -o ../build/EmbreeViewportRendererIXP.so -DBits64_ -m64 -DUNIX -D_BOOL -DLINUX -DFUNCPROTO -D_GNU_SOURCE -DLINUX_64 -fPIC -fno-strict-aliasing -DREQUIRE_IOSTREAM -O3 -Wall -Wno-multichar -Wno-comment -Wno-sign-compare -funsigned-char -pthread -g   -Wno-deprecated -Wno-reorder -ftemplate-depth-25 -fno-gnu-keywords -Wl,-Bsymbolic -shared -Wl,--version-script=../EmbreeViewportRenderer/linux_plugin.map -L../build -L/usr/autodesk/maya2014-x64/lib   ../build/EmbreeViewportRenderer.o ../build/EmbreeViewportRendererPluginIXP.o -L/usr/autodesk/maya2014-x64/lib   -lOpenMayaRender -lOpenMaya -lOpenMayaUI -lFoundation ../build/libsys.a ../build/liblexers.a ../build/libloaders.a ../build/libimage.a ../build/libdevice.a ../build/liblexers.a ../build/libsys.a -lpthread -ldl   /opt/intel/composer_xe_2015.0.090/compiler/lib/intel64/libimf.a /opt/intel/composer_xe_2015.0.090/compiler/lib/intel64/libirc.a
cc  -o ../build/EmbreeViewportRendererIXP.so -DBits64_ -m64 -DUNIX -D_BOOL -DLINUX -DFUNCPROTO -D_GNU_SOURCE -DLINUX_64 -fPIC -fno-strict-aliasing -DREQUIRE_IOSTREAM -O3 -Wall -Wno-multichar -Wno-comment -Wno-sign-compare -funsigned-char -pthread -g   -Wno-deprecated -Wno-reorder -ftemplate-depth-25 -fno-gnu-keywords -Wl,-Bsymbolic -shared -Wl,--version-script=$MAYAPLUGINS/linux_plugin.map -L../build -L$MAYALIBS   ../build/EmbreeViewportRenderer.o ../build/EmbreeViewportRendererPluginIXP.o -L$MAYALIBS   -lOpenMayaRender -lOpenMaya -lOpenMayaUI -lFoundation ../build/libsys.a ../build/liblexers.a ../build/libloaders.a ../build/libimage.a ../build/libdevice.a ../build/liblexers.a ../build/libsys.a -lpthread -ldl  $INTELCOMPILERLIBS/libimf.a $INTELCOMPILERLIBS/libirc.a

